@startuml
title CI/CD workflow
box codebase
participant develop
collections "feature/newfeature" as feature
collections "release/vX.X.X" as release
participant master
end box
box CI/CD
participant "github \n actions" as ci
participant "run-tests" as unit
participant "build-and-release" as build
participant "deploy-to-staging" as deploystaging
participant "deploy-to-prod" as deployprod
end box
box kubernetes
participant staging
participant prod
end box
database dockerhub

group feature branches
|||
create feature
develop -> feature : branch
activate feature
feature -> feature : awesome \n changes
return pull request
deactivate feature
destroy feature
== build ==
develop --> ci : triggers event
create unit
ci -> unit : triggers job
activate unit
create build
unit -> build : tests ok
destroy unit
activate build
build -> build : build and tag docker image
build -> dockerhub : push image to registry
build -> ci : end of worklow
destroy build
end

group release branches
|||
create release
develop -> release : branch

activate release
release -> master : pull request
release -> develop : pull request
deactivate release
destroy release
== build and deploy to staging ==
develop --> ci : triggers event
create unit
ci -> unit : triggers job
activate unit
create build
unit -> build : tests ok
destroy unit
activate build
build -> build : build and tag docker image
build -> dockerhub : push image to registry
|||
create deploystaging
build -> deploystaging
destroy build
activate deploystaging
deploystaging -> staging : deploy to namespace "staging"
staging -> dockerhub : pull docker image
dockerhub -> staging : <image>:sha-${GITHUB_SHA::7}
staging -> deploystaging : deploy ok
deploystaging -> ci : end of workflow
destroy deploystaging
== build and deploy to prod ==
master --> ci : triggers event
create unit
ci -> unit : triggers job
activate unit
create build
unit -> build : tests ok
destroy unit
activate build
build -> build : build and tag docker image
build -> dockerhub : push image to registry
|||
create deployprod
build -> deployprod
destroy build
activate deployprod
deployprod -> prod : deploy to namespace "staging"
prod -> dockerhub : pull docker image
dockerhub -> prod : <image>:sha-${GITHUB_SHA::7}
prod -> deployprod : deploy ok
deployprod -> ci : end of workflow
destroy deployprod
end

@enduml