apiVersion: v1
kind: Service
metadata:
  name: clickcount-app
  labels:
    run: clickcount-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    run: clickcount-app
