namespace: prod

resources:
  - app/deployment.yaml
  - app/service.yaml
  - redis/pv-volume.yaml
  - redis/pvc.yaml
  - redis/deployment.yaml
  - redis/service.yaml

images:
  - name: REPOSITORY:TAG
    newName: osgoifo/clickcount
    newTag: latest
