name: main-worklfow

env:
  IMAGE_REPOSITORY: osgoifo/clickcount
  KUBECTL_VERSION: '1.14.10'
  KUSTOMIZE_VERSION: '3.5.4'

on:
  push:
    branches:
      - master
      - develop
    tags:
    
  pull_request:
    branches:
      - master
      - develop
      - feature/**

jobs:
  # Run all unit tests.
  run-tests:
    #runs-on: ubuntu-latest
    runs-on: [self-hosted, linux, X64]
    steps:
      # Check out the pull request's source code.
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Show maven version
        run: mvn --version

      # Run unit tests.
      - name: Run unit tests
        run: mvn test # there are no unit test (yet), but there definitely should

  # Build and release.
  build-and-release:
    #runs-on: ubuntu-latest
    runs-on: [self-hosted, linux, X64]
    needs:
      - run-tests
    steps:
      # Check out source code.
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.IMAGE_REPOSITORY }}:latest,${{ env.IMAGE_REPOSITORY }}:sha-${{ github.sha }}


  # Deploy to Kubernetes.
  deploy-to-staging:
    #runs-on: ubuntu-latest
    runs-on: [self-hosted, linux, X64]
    if: github.ref == 'refs/heads/master'
    needs:
      - build-and-release
    env:
      KUBECONFIG: kubeconfig.yml
      SERVICE_ACCOUNT_NAME: github-actions
      NAMESPACE: staging
    steps:
      # Check out source code.
      - name: Check out source code
        uses: actions/checkout@v2

      # Set up kubectl.
      - name: Set up kubectl
        run: |-
          curl -sfLo kubectl https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # Configure kubectl.
      - name: Configure kubectl
        run: echo ${{ secrets.KUBECONFIG }} | base64 --decode > ${KUBECONFIG:?}

      # Kustomize Kubernetes resources.
      - name: Kustomize Kubernetes resources
        working-directory: ./manifests
        run: |-
          kustomize edit set namespace $NAMESPACE
          kustomize edit set image REPOSITORY:TAG=${IMAGE_REPOSITORY}:sha-${{ github.sha }}

      # Deploy to Kubernetes.
      - name: Deploy to Kubernetes
        run: |-
          CLUSTER_NAME=$(kubectl config get-contexts "$(kubectl config current-context)" | awk '{print $3}' | tail -n 1)
          kubectl config use-context "${SERVICE_ACCOUNT_NAME}-${NAMESPACE}-${CLUSTER_NAME}"
          kubectl apply --kustomize manifests/

      # Validate deployment.
      - name: Validate deployment
        run: kubectl rollout status --timeout 120s deployment/clickcount-app -n $NAMESPACE

  # Deploy to Kubernetes.
  deploy-to-prod:
    #runs-on: ubuntu-latest
    runs-on: [self-hosted, linux, X64]
    if: github.ref == 'refs/heads/master' && github.event_name == 'tag'
    needs:
      - build-and-release
    env:
      KUBECONFIG: kubeconfig.yml
      SERVICE_ACCOUNT_NAME: github-actions
      NAMESPACE: prod
    steps:
      # Check out source code.
      - name: Check out source code
        uses: actions/checkout@v2

      # Set up kubectl.
      - name: Set up kubectl
        run: |-
          curl -sfLo kubectl https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # Configure kubectl.
      - name: Configure kubectl
        run: echo ${{ secrets.KUBECONFIG }} | base64 --decode > ${KUBECONFIG:?}

      # Kustomize Kubernetes resources.
      - name: Kustomize Kubernetes resources
        working-directory: ./manifests
        run: |-
          kustomize edit set namespace $NAMESPACE
          kustomize edit set image REPOSITORY:TAG=${IMAGE_REPOSITORY}:sha-${{ github.sha }}

      # Deploy to Kubernetes.
      - name: Deploy to Kubernetes
        run: |-
          CLUSTER_NAME=$(kubectl config get-contexts "$(kubectl config current-context)" | awk '{print $3}' | tail -n 1)
          kubectl config use-context "${SERVICE_ACCOUNT_NAME}-${NAMESPACE}-${CLUSTER_NAME}"
          kubectl apply --kustomize manifests/

      # Validate deployment.
      - name: Validate deployment
        run: kubectl rollout status --timeout 120s deployment/clickcount-app -n $NAMESPACE
